server:
  port: 8081

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # --- Route for Lunch service ---
        - id: lunch_service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/lunch/**   # Match all Lunch API paths
          filters:
            - StripPrefix=0
            - RewritePath=/api/v1/lunch/(?<rest>.*), /api/v1/${rest} # remove lunch from path and send to Lunch service

        # --- Route for Auth service ---
        - id: auth_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**    # Send login/signup to Auth service
          filters:
            - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/oauth2/jwks
