server:
  port: 8081

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        # --- Route for Lunch service ---
        # TODO add lunch to path
        - id: lunch_service
          uri: http://localhost:8080
          predicates:
            - Path=/lunch/api/v1/**         # Match all Lunch API paths
          filters:
            - StripPrefix=0           # Keep full path since Lunch also uses /api/v1

        # --- Route for Auth service ---
        - id: auth_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**    # Send login/signup to Auth service
          filters:
            - StripPrefix=0

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "change-me-to-a-long-random-string-which-is-more-than-32-characters"   # must match Auth service secret
          issuer-uri: "http://localhost:8082"
